### ISSUE TITLE
캐싱 오류??

### ISSUE THREAD

**Issue by leezzangmin** [leezzangmin/SpringCafeProject#132]
2022-12-06 03:36:58.122 ERROR 1 --- [p-nio-80-exec-3] c.z.g.c.e.c.GlobalErrorController        : handleEntityNotFoundException

org.springframework.data.redis.serializer.SerializationException: Could not read JSON: Cannot construct instance of `com.zzangmin.gesipan.component.basiccrud.dto.post.PostResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"["com.zzangmin.gesipan.component.basiccrud.dto.post.PostResponse",{"postId":6734,"userId":5100,"userNickname":"burnskrista","hitCount":3,"recommendCount":2,"postSubject":"Policy group realize seat.","postContent":"Become whole local. Question shoulder hit maintain example call. Professor imagine reason project next instead. Level test spring although would still factor.","createdAt":"2020-03-26T14:58:29","updatedAt":"2020-03-26T14:58:29","comments":["java.util.ArrayList",[["com.zzangmin.gesipan."[truncated 352 bytes]; line: 1, column: 68]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.zzangmin.gesipan.component.basiccrud.dto.post.PostResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"["com.zzangmin.gesipan.component.basiccrud.dto.post.PostResponse",{"postId":6734,"userId":5100,"userNickname":"burnskrista","hitCount":3,"recommendCount":2,"postSubject":"Policy group realize seat.","postContent":"Become whole local. Question shoulder hit maintain example call. Professor imagine reason project next instead. Level test spring although would still factor.","createdAt":"2020-03-26T14:58:29","updatedAt":"2020-03-26T14:58:29","comments":["java.util.ArrayList",[["com.zzangmin.gesipan."[truncated 352 bytes]; line: 1, column: 68]
        at org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer.deserialize(GenericJackson2JsonRedisSerializer.java:157) ~[spring-data-redis-2.7.0.jar!/:2.7.0]
        at org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer.deserialize(GenericJackson2JsonRedisSerializer.java:135) ~[spring-data-redis-2.7.0.jar!/:2.7.0]

**Comment by leezzangmin** [comment]
성능테스트하고 있는데 이런 에러가!!
https://eeyatho.tistory.com/5

**Comment by leezzangmin** [comment]
https://velog.io/@wisdom08/cannot-deserialize-from-Object-value-%EC%97%90%EB%9F%AC
